/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia3;

import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Velo
 */
public final class ejercicio6ejemplo extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio6
     */
    public ejercicio6ejemplo() {
        initComponents();
        agregar(false);
        confirmarEspe.setVisible(false);
       

        
    }
    
    public void agregar(boolean b)
    {
        jAgregar.setVisible(b);
        txtAgregar.setEnabled(b);
        txtAgregar.setVisible(b);
        confirmar.setVisible(b);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deporte = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        BtnAgregar = new javax.swing.JButton();
        jAgregar = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        borrarTodo = new javax.swing.JButton();
        btnBorrarEspe = new javax.swing.JButton();
        confirmarEspe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basket", "Futboll", "Natacion", "Voley", "Handball" }));

        jLabel1.setText("Deporte:");

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jAgregar.setText("Agregar:");

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        borrarTodo.setText("Borrar Todo");
        borrarTodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                borrarTodoItemStateChanged(evt);
            }
        });
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });

        btnBorrarEspe.setText("Borrar Especifico");
        btnBorrarEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEspeActionPerformed(evt);
            }
        });

        confirmarEspe.setText("Confirmar");
        confirmarEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEspeActionPerformed(evt);
            }
        });

        jLabel2.setText("Borrar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(borrarTodo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorrarEspe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirmarEspe)
                                .addGap(98, 98, 98)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregar)
                    .addComponent(jAgregar)
                    .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarEspe)
                    .addComponent(confirmarEspe)
                    .addComponent(jLabel2)
                    .addComponent(lblMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrarTodo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        agregar(true);
        
        
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
        String msj = "";
        
        if(!txtAgregar.getText().isEmpty())
        {  
            msj = txtAgregar.getText();
            txtAgregar.setText("");
            deporte.addItem(msj);
        }
        
        agregar(false);
    }//GEN-LAST:event_confirmarActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        // TODO add your handling code here:
        if(deporte.getItemCount()>0) deporte.removeAllItems();
        else{
            JOptionPane.showMessageDialog(rootPane, "Lista Vacia");
        }
        
        
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void borrarTodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_borrarTodoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_borrarTodoItemStateChanged

    private void btnBorrarEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEspeActionPerformed
        // TODO add your handling code here:
        if(deporte.getItemCount()>0)
        {
            String msj = "";
            msj = deporte.getSelectedItem().toString();
        
            lblMostrar.setText(msj);
        
            confirmarEspe.setVisible(true);
        }
        
        

        
    }//GEN-LAST:event_btnBorrarEspeActionPerformed

    private void confirmarEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEspeActionPerformed
        // TODO add your handling code here:
        if(deporte.getItemCount()>0) deporte.removeItemAt(deporte.getSelectedIndex());
        
    }//GEN-LAST:event_confirmarEspeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio6ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio6ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio6ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio6ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio6ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton btnBorrarEspe;
    private javax.swing.JButton confirmar;
    private javax.swing.JButton confirmarEspe;
    private javax.swing.JComboBox<String> deporte;
    private javax.swing.JLabel jAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JTextField txtAgregar;
    // End of variables declaration//GEN-END:variables
}
