/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia3;

import javax.swing.JOptionPane;

/**
 *
 * @author velor
 */
public class ejercicio8 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio8
     */
    public ejercicio8() {
        initComponents();
        mostrar(false);
        setLocationRelativeTo(null);
        
    }
    
    public void mostrar(boolean b)
    {
        txtAgregar.setVisible(b);
        aceptar.setVisible(b);
        
    }


        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        provincias = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        txtAgregar = new javax.swing.JTextField();
        aceptar = new javax.swing.JButton();
        borrarSele = new javax.swing.JButton();
        borrarTo = new javax.swing.JButton();
        borrarUlt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Provincias de Argentina:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        getContentPane().add(provincias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 246, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));
        getContentPane().add(txtAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 34, 225, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 34, -1, -1));

        borrarSele.setText("Borrar Seleccionada");
        borrarSele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarSeleActionPerformed(evt);
            }
        });
        getContentPane().add(borrarSele, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, 380, -1));

        borrarTo.setText("Borrar Todo");
        borrarTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarToActionPerformed(evt);
            }
        });
        getContentPane().add(borrarTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 380, -1));

        borrarUlt.setText("Borrar Ultima");
        borrarUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUltActionPerformed(evt);
            }
        });
        getContentPane().add(borrarUlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        mostrar(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        provincias.addItem(txtAgregar.getText());
        
        txtAgregar.setText("");
        
        mostrar(false);
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void borrarSeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarSeleActionPerformed
        // TODO add your handling code here:
        
        String msj = "";
        
        msj = provincias.getSelectedItem().toString();
        if(provincias.getItemCount()>0)
        {
            provincias.removeItemAt(provincias.getSelectedIndex());
            JOptionPane.showMessageDialog(rootPane, "Se elimino el elemento: "+msj);
        }
    }//GEN-LAST:event_borrarSeleActionPerformed

    private void borrarToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarToActionPerformed
        // TODO add your handling code here:
        if(provincias.getItemCount()>0) provincias.removeAllItems();
    }//GEN-LAST:event_borrarToActionPerformed

    private void borrarUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUltActionPerformed
        // TODO add your handling code here:
        String msj = "";
        
        provincias.setSelectedIndex(provincias.getItemCount()-1);
        msj = provincias.getSelectedItem().toString(); 
        provincias.removeItemAt(provincias.getItemCount()-1);
        
        JOptionPane.showMessageDialog(rootPane, "Se borro el elemento: "+ msj);
    }//GEN-LAST:event_borrarUltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton borrarSele;
    private javax.swing.JButton borrarTo;
    private javax.swing.JButton borrarUlt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> provincias;
    private javax.swing.JTextField txtAgregar;
    // End of variables declaration//GEN-END:variables
}
