/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

import static java.awt.Color.black;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Velo
 */
public class deportes extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public deportes() {
        initComponents();
        setTitle("Ejercicio Check Box");
        ocultarNiveles();
        
    }
    
    public void ocultarNiveles()
        {
            inicialV.setVisible(false);
            inicialF.setVisible(false);
            inicialB.setVisible(false);
            inicialN.setVisible(false);

            medioV.setVisible(false);
            medioF.setVisible(false);
            medioB.setVisible(false);
            medioN.setVisible(false);

            avanzadoV.setVisible(false);
            avanzadoF.setVisible(false);
            avanzadoB.setVisible(false);
            avanzadoN.setVisible(false);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        voley = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        futball = new javax.swing.JCheckBox();
        basketball = new javax.swing.JCheckBox();
        natacion = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        mañana = new javax.swing.JCheckBox();
        tarde = new javax.swing.JCheckBox();
        noche = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        inicialV = new javax.swing.JCheckBox();
        medioV = new javax.swing.JCheckBox();
        avanzadoV = new javax.swing.JCheckBox();
        medioF = new javax.swing.JCheckBox();
        avanzadoF = new javax.swing.JCheckBox();
        inicialF = new javax.swing.JCheckBox();
        medioB = new javax.swing.JCheckBox();
        avanzadoB = new javax.swing.JCheckBox();
        inicialB = new javax.swing.JCheckBox();
        medioN = new javax.swing.JCheckBox();
        avanzadoN = new javax.swing.JCheckBox();
        inicialN = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        voley.setText("Voley");
        voley.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voleyActionPerformed(evt);
            }
        });
        getContentPane().add(voley, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 22, -1, -1));

        jLabel2.setText("Deporte:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, -1, -1));

        futball.setText("Futball");
        futball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futballActionPerformed(evt);
            }
        });
        getContentPane().add(futball, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 48, -1, -1));

        basketball.setText("Basketball");
        basketball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketballActionPerformed(evt);
            }
        });
        getContentPane().add(basketball, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 74, -1, -1));

        natacion.setText("Natacion");
        natacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                natacionActionPerformed(evt);
            }
        });
        getContentPane().add(natacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 100, -1, -1));

        jLabel3.setText("Horarios:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 142, -1, -1));

        mañana.setText("Mañana");
        getContentPane().add(mañana, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        tarde.setText("Tarde");
        getContentPane().add(tarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 166, -1, -1));

        noche.setText("Noche");
        getContentPane().add(noche, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 192, -1, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, -1, -1));

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        inicialV.setText("Inicial");
        getContentPane().add(inicialV, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 22, -1, -1));

        medioV.setText("Medio");
        getContentPane().add(medioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 22, -1, -1));

        avanzadoV.setText("Avanzado");
        getContentPane().add(avanzadoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 22, -1, -1));

        medioF.setText("Medio");
        getContentPane().add(medioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 48, -1, -1));

        avanzadoF.setText("Avanzado");
        getContentPane().add(avanzadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 48, -1, -1));

        inicialF.setText("Inicial");
        getContentPane().add(inicialF, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 48, -1, -1));

        medioB.setText("Medio");
        getContentPane().add(medioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 74, -1, -1));

        avanzadoB.setText("Avanzado");
        getContentPane().add(avanzadoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 74, -1, -1));

        inicialB.setText("Inicial");
        getContentPane().add(inicialB, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 74, -1, -1));

        medioN.setText("Medio");
        getContentPane().add(medioN, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 100, -1, -1));

        avanzadoN.setText("Avanzado");
        getContentPane().add(avanzadoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 100, -1, -1));

        inicialN.setText("Inicial");
        getContentPane().add(inicialN, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 100, -1, -1));

        mostrar.setEditable(false);
        mostrar.setColumns(20);
        mostrar.setRows(5);
        mostrar.setEnabled(false);
        jScrollPane2.setViewportView(mostrar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 126, 220, 100));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String msj = "Selecciono el deporte:";
        
        
        if(voley.isSelected()) msj+="\nvoley";
        if(inicialV.isSelected()) msj+=" Inicial";
        if(medioV.isSelected()) msj+=" Medio";
        if(avanzadoV.isSelected()) msj+=" Avanzado";
        
        if(futball.isSelected()) msj+="\nFutball";
        if(inicialF.isSelected()) msj+=" Inicial";
        if(medioF.isSelected()) msj+=" Medio";
        if(avanzadoF.isSelected()) msj+=" Avanzado";
                
        if(basketball.isSelected()) msj+="\nBasquetball";
        if(inicialB.isSelected()) msj+=" Inicial";
        if(medioB.isSelected()) msj+=" Medio";
        if(avanzadoB.isSelected()) msj+=" Avanzado";
        
        if(natacion.isSelected()) msj+="\nNatacion";
        if(inicialN.isSelected()) msj+=" Inicial";
        if(medioN.isSelected()) msj+=" Medio";
        if(avanzadoN.isSelected()) msj+=" Avanzado";
        
        msj+= "\n"+"\nEn el turno: ";
        
        if(mañana.isSelected()) msj+="\nMañana";
        if(tarde.isSelected()) msj+="\nTarde";
        if(noche.isSelected()) msj+="\nNoche";
            
        mostrar.setText(msj);
        mostrar.setDisabledTextColor(black);
        
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        
        voley.setSelected(false);
        futball.setSelected(false);
        basketball.setSelected(false);
        natacion.setSelected(false);
        
        mañana.setSelected(false);
        tarde.setSelected(false);
        noche.setSelected(false);
        
        inicialV.setSelected(false);
        medioV.setSelected(false);
        avanzadoV.setSelected(false);
        
        inicialF.setSelected(false);
        medioF.setSelected(false);
        avanzadoF.setSelected(false);
        
        inicialB.setSelected(false);
        medioB.setSelected(false);
        avanzadoB.setSelected(false);
        
        inicialN.setSelected(false);
        medioN.setSelected(false);
        avanzadoN.setSelected(false);
        
        ocultarNiveles();
        
        mostrar.setText("");
        
        
        
    }//GEN-LAST:event_borrarActionPerformed

    private void voleyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voleyActionPerformed
        // TODO add your handling code here:
        if(voley.isSelected())
        {
            inicialV.setVisible(true);
            medioV.setVisible(true);
            avanzadoV.setVisible(true);
        }
        else{
            inicialV.setVisible(false);
            medioV.setVisible(false);
            avanzadoV.setVisible(false);
        }
    }//GEN-LAST:event_voleyActionPerformed

    private void futballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futballActionPerformed
        // TODO add your handling code here:
        if(futball.isSelected())
            {
                inicialF.setVisible(true);
                medioF.setVisible(true);
                avanzadoF.setVisible(true);
            }
        else{
                inicialF.setVisible(false);
                medioF.setVisible(false);
                avanzadoF.setVisible(false);
            }
    }//GEN-LAST:event_futballActionPerformed

    private void basketballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketballActionPerformed
        // TODO add your handling code here:
        if(basketball.isSelected())
            {
                inicialB.setVisible(true);
                medioB.setVisible(true);
                avanzadoB.setVisible(true);
            }
            else{
                inicialB.setVisible(false);
                medioB.setVisible(false);
                avanzadoB.setVisible(false);
            }
    }//GEN-LAST:event_basketballActionPerformed

    private void natacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_natacionActionPerformed
        // TODO add your handling code here:
        if(natacion.isSelected())
            {
                inicialN.setVisible(true);
                medioN.setVisible(true);
                avanzadoN.setVisible(true);
            }
            else{
                inicialN.setVisible(false);
                medioN.setVisible(false);
                avanzadoN.setVisible(false);
            }
    }//GEN-LAST:event_natacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        principal obj = new principal();
        
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox avanzadoB;
    private javax.swing.JCheckBox avanzadoF;
    private javax.swing.JCheckBox avanzadoN;
    private javax.swing.JCheckBox avanzadoV;
    private javax.swing.JCheckBox basketball;
    private javax.swing.JButton borrar;
    private javax.swing.JCheckBox futball;
    private javax.swing.JCheckBox inicialB;
    private javax.swing.JCheckBox inicialF;
    private javax.swing.JCheckBox inicialN;
    private javax.swing.JCheckBox inicialV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox mañana;
    private javax.swing.JCheckBox medioB;
    private javax.swing.JCheckBox medioF;
    private javax.swing.JCheckBox medioN;
    private javax.swing.JCheckBox medioV;
    private javax.swing.JTextArea mostrar;
    private javax.swing.JCheckBox natacion;
    private javax.swing.JCheckBox noche;
    private javax.swing.JCheckBox tarde;
    private javax.swing.JCheckBox voley;
    // End of variables declaration//GEN-END:variables
}
