/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Velo
 */
public final class ejercicio7 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio7
     */
    public ejercicio7() {
        initComponents();
        ocultarTipos();
    }
    
    public void ocultarTipos()
    {
        casaAgp.setVisible(false);
        casaCgt.setVisible(false);
        casaCh2.setVisible(false);
        casaIntevu.setVisible(false);
        casaMutual.setVisible(false);
        casaDanes.setVisible(false);
        
        dpto1Agp.setVisible(false);
        dpto1Cgt.setVisible(false);
        dpto1Ch2.setVisible(false);
        dpto1Danes.setVisible(false);
        dpto1Intevu.setVisible(false);
        dpto1Mutual.setVisible(false);
        
        dpto2Agp.setVisible(false);
        dpto2Cgt.setVisible(false);
        dpto2Ch2.setVisible(false);
        dpto2Danes.setVisible(false);
        dpto2Intevu.setVisible(false);
        dpto2Mutual.setVisible(false);
        
        localAgp.setVisible(false);
        localCgt.setVisible(false);
        localCh2.setVisible(false);
        localDanes.setVisible(false);
        localIntevu.setVisible(false);
        localMutual.setVisible(false);
        
        galponAgp.setVisible(false);
        galponCgt.setVisible(false);
        galponCh2.setVisible(false);
        galponDanes.setVisible(false);
        galponIntevu.setVisible(false);
        galponMutual.setVisible(false);
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoIntevu = new javax.swing.ButtonGroup();
        tipoDanes = new javax.swing.ButtonGroup();
        tipoAgp = new javax.swing.ButtonGroup();
        tipoMutual = new javax.swing.ButtonGroup();
        tipoCgt = new javax.swing.ButtonGroup();
        tipoCh2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        intevu = new javax.swing.JRadioButton();
        agp = new javax.swing.JRadioButton();
        mutual = new javax.swing.JRadioButton();
        danes = new javax.swing.JRadioButton();
        cgt = new javax.swing.JRadioButton();
        ch2 = new javax.swing.JRadioButton();
        casaIntevu = new javax.swing.JRadioButton();
        dpto1Intevu = new javax.swing.JRadioButton();
        dpto2Intevu = new javax.swing.JRadioButton();
        localIntevu = new javax.swing.JRadioButton();
        galponIntevu = new javax.swing.JRadioButton();
        casaDanes = new javax.swing.JRadioButton();
        dpto1Danes = new javax.swing.JRadioButton();
        dpto2Danes = new javax.swing.JRadioButton();
        localDanes = new javax.swing.JRadioButton();
        galponDanes = new javax.swing.JRadioButton();
        casaAgp = new javax.swing.JRadioButton();
        dpto1Agp = new javax.swing.JRadioButton();
        dpto2Agp = new javax.swing.JRadioButton();
        localAgp = new javax.swing.JRadioButton();
        galponAgp = new javax.swing.JRadioButton();
        casaMutual = new javax.swing.JRadioButton();
        dpto1Mutual = new javax.swing.JRadioButton();
        dpto2Mutual = new javax.swing.JRadioButton();
        localMutual = new javax.swing.JRadioButton();
        galponMutual = new javax.swing.JRadioButton();
        casaCgt = new javax.swing.JRadioButton();
        dpto1Cgt = new javax.swing.JRadioButton();
        dpto2Cgt = new javax.swing.JRadioButton();
        localCgt = new javax.swing.JRadioButton();
        galponCgt = new javax.swing.JRadioButton();
        casaCh2 = new javax.swing.JRadioButton();
        dpto1Ch2 = new javax.swing.JRadioButton();
        dpto2Ch2 = new javax.swing.JRadioButton();
        localCh2 = new javax.swing.JRadioButton();
        galponCh2 = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de alquileres");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 6, -1, -1));

        intevu.setText("Bº Intevu");
        intevu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intevuActionPerformed(evt);
            }
        });
        getContentPane().add(intevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));

        agp.setText("Bº AGP");
        agp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agpActionPerformed(evt);
            }
        });
        getContentPane().add(agp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        mutual.setText("Bº Mutual");
        mutual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutualActionPerformed(evt);
            }
        });
        getContentPane().add(mutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, -1, -1));

        danes.setText("Bº Danes");
        danes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danesActionPerformed(evt);
            }
        });
        getContentPane().add(danes, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, -1));

        cgt.setText("Bº CGT");
        cgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgtActionPerformed(evt);
            }
        });
        getContentPane().add(cgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        ch2.setText("Bº Chacra 2");
        ch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2ActionPerformed(evt);
            }
        });
        getContentPane().add(ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, -1, -1));

        tipoIntevu.add(casaIntevu);
        casaIntevu.setText("Casa");
        getContentPane().add(casaIntevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 34, -1, -1));

        tipoIntevu.add(dpto1Intevu);
        dpto1Intevu.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Intevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 34, -1, -1));

        tipoIntevu.add(dpto2Intevu);
        dpto2Intevu.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Intevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 34, -1, -1));

        tipoIntevu.add(localIntevu);
        localIntevu.setText("Local");
        getContentPane().add(localIntevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 34, -1, -1));

        tipoIntevu.add(galponIntevu);
        galponIntevu.setText("Galpon");
        getContentPane().add(galponIntevu, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 34, -1, -1));

        tipoDanes.add(casaDanes);
        casaDanes.setText("Casa");
        getContentPane().add(casaDanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 60, -1, -1));

        tipoDanes.add(dpto1Danes);
        dpto1Danes.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Danes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        tipoDanes.add(dpto2Danes);
        dpto2Danes.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Danes, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 60, -1, -1));

        tipoDanes.add(localDanes);
        localDanes.setText("Local");
        getContentPane().add(localDanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 60, -1, -1));

        tipoDanes.add(galponDanes);
        galponDanes.setText("Galpon");
        getContentPane().add(galponDanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 60, -1, -1));

        tipoAgp.add(casaAgp);
        casaAgp.setText("Casa");
        getContentPane().add(casaAgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 86, -1, -1));

        tipoAgp.add(dpto1Agp);
        dpto1Agp.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Agp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 86, -1, -1));

        tipoAgp.add(dpto2Agp);
        dpto2Agp.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Agp, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 86, -1, -1));

        tipoAgp.add(localAgp);
        localAgp.setText("Local");
        getContentPane().add(localAgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 86, -1, -1));

        tipoAgp.add(galponAgp);
        galponAgp.setText("Galpon");
        getContentPane().add(galponAgp, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 86, -1, -1));

        tipoMutual.add(casaMutual);
        casaMutual.setText("Casa");
        getContentPane().add(casaMutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 112, -1, -1));

        tipoMutual.add(dpto1Mutual);
        dpto1Mutual.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Mutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 112, -1, -1));

        tipoMutual.add(dpto2Mutual);
        dpto2Mutual.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Mutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 112, -1, -1));

        tipoMutual.add(localMutual);
        localMutual.setText("Local");
        getContentPane().add(localMutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 112, -1, -1));

        tipoMutual.add(galponMutual);
        galponMutual.setText("Galpon");
        getContentPane().add(galponMutual, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 112, -1, -1));

        tipoCgt.add(casaCgt);
        casaCgt.setText("Casa");
        getContentPane().add(casaCgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 138, -1, -1));

        tipoCgt.add(dpto1Cgt);
        dpto1Cgt.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Cgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 138, -1, -1));

        tipoCgt.add(dpto2Cgt);
        dpto2Cgt.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Cgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 138, -1, -1));

        tipoCgt.add(localCgt);
        localCgt.setText("Local");
        getContentPane().add(localCgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 138, -1, -1));

        tipoCgt.add(galponCgt);
        galponCgt.setText("Galpon");
        getContentPane().add(galponCgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 138, -1, -1));

        tipoCh2.add(casaCh2);
        casaCh2.setText("Casa");
        getContentPane().add(casaCh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 164, -1, -1));

        tipoCh2.add(dpto1Ch2);
        dpto1Ch2.setText("Dpto. 1 Dormitorio");
        getContentPane().add(dpto1Ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 164, -1, -1));

        tipoCh2.add(dpto2Ch2);
        dpto2Ch2.setText("Dto. 2 Dormitorios");
        getContentPane().add(dpto2Ch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 164, -1, -1));

        tipoCh2.add(localCh2);
        localCh2.setText("Local");
        getContentPane().add(localCh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 164, -1, -1));

        tipoCh2.add(galponCh2);
        galponCh2.setText("Galpon");
        getContentPane().add(galponCh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 164, -1, -1));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 196, -1, -1));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 196, -1, -1));

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        tipoAgp.clearSelection();
        tipoCgt.clearSelection();
        tipoCh2.clearSelection();
        tipoDanes.clearSelection();
        tipoIntevu.clearSelection();
        tipoMutual.clearSelection();
        
        agp.setSelected(false);
        cgt.setSelected(false);
        ch2.setSelected(false);
        danes.setSelected(false);
        intevu.setSelected(false);
        mutual.setSelected(false);
        
        ocultarTipos();
        
        
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void intevuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intevuActionPerformed
        // TODO add your handling code here:
        if(intevu.isSelected()) 
        {
            casaIntevu.setVisible(true);
            dpto1Intevu.setVisible(true);
            dpto2Intevu.setVisible(true);
            localIntevu.setVisible(true);
            galponIntevu.setVisible(true);
        }
        else{
            casaIntevu.setVisible(false);
            dpto1Intevu.setVisible(false);
            dpto2Intevu.setVisible(false);
            localIntevu.setVisible(false);
            galponIntevu.setVisible(false);
            tipoIntevu.clearSelection();
            
        }
    }//GEN-LAST:event_intevuActionPerformed

    private void danesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danesActionPerformed
        // TODO add your handling code here:
        if(danes.isSelected()) 
        {
            casaDanes.setVisible(true);
            dpto1Danes.setVisible(true);
            dpto2Danes.setVisible(true);
            localDanes.setVisible(true);
            galponDanes.setVisible(true);
        }
        else{
            casaDanes.setVisible(false);
            dpto1Danes.setVisible(false);
            dpto2Danes.setVisible(false);
            localDanes.setVisible(false);
            galponDanes.setVisible(false);
            tipoDanes.clearSelection();
        }
    }//GEN-LAST:event_danesActionPerformed

    private void agpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agpActionPerformed
        // TODO add your handling code here:
        if(agp.isSelected()) 
        {
            casaAgp.setVisible(true);
            dpto1Agp.setVisible(true);
            dpto2Agp.setVisible(true);
            localAgp.setVisible(true);
            galponAgp.setVisible(true);
        }
        else{
            casaAgp.setVisible(false);
            dpto1Agp.setVisible(false);
            dpto2Agp.setVisible(false);
            localAgp.setVisible(false);
            galponAgp.setVisible(false);
            tipoAgp.clearSelection();
            
        }
    }//GEN-LAST:event_agpActionPerformed

    private void mutualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutualActionPerformed
        // TODO add your handling code here:
        if(mutual.isSelected()) 
        {
            casaMutual.setVisible(true);
            dpto1Mutual.setVisible(true);
            dpto2Mutual.setVisible(true);
            localMutual.setVisible(true);
            galponMutual.setVisible(true);
        }
        else{
            casaMutual.setVisible(false);
            dpto1Mutual.setVisible(false);
            dpto2Mutual.setVisible(false);
            localMutual.setVisible(false);
            galponMutual.setVisible(false);
            tipoMutual.clearSelection();
        }
        
    }//GEN-LAST:event_mutualActionPerformed

    private void cgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgtActionPerformed
        // TODO add your handling code here:
        if(cgt.isSelected()) 
        {
            casaCgt.setVisible(true);
            dpto1Cgt.setVisible(true);
            dpto2Cgt.setVisible(true);
            localCgt.setVisible(true);
            galponCgt.setVisible(true);
        }
        else{
            casaCgt.setVisible(false);
            dpto1Cgt.setVisible(false);
            dpto2Cgt.setVisible(false);
            localCgt.setVisible(false);
            galponCgt.setVisible(false);
            tipoCgt.clearSelection();
        }
    }//GEN-LAST:event_cgtActionPerformed

    private void ch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2ActionPerformed
        // TODO add your handling code here:
        if(ch2.isSelected()) 
        {
            casaCh2.setVisible(true);
            dpto1Ch2.setVisible(true);
            dpto2Ch2.setVisible(true);
            localCh2.setVisible(true);
            galponCh2.setVisible(true);
        } 
        else{
            casaCh2.setVisible(false);
            dpto1Ch2.setVisible(false);
            dpto2Ch2.setVisible(false);
            localCh2.setVisible(false);
            galponCh2.setVisible(false);
            tipoCh2.clearSelection();
        }
    }//GEN-LAST:event_ch2ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String msj = "Usted elijio: ";
        
        if(intevu.isSelected())
        {
            msj+= "\n " + intevu.getText();
            if(casaIntevu.isSelected()) msj+= " " + casaIntevu.getText();
            if(dpto1Intevu.isSelected()) msj+= " " + dpto1Intevu.getText();
            if(dpto2Intevu.isSelected()) msj+= " " + dpto2Intevu.getText();
            if(localIntevu.isSelected()) msj+= " " + localIntevu.getText();
            if(galponIntevu.isSelected()) msj+= " " + galponIntevu.getText();
        }
        
        if(danes.isSelected())
        {
            msj+= "\n " + danes.getText();
            if(casaDanes.isSelected()) msj+= " " + casaDanes.getText();
            if(dpto1Danes.isSelected()) msj+= " " + dpto1Danes.getText();
            if(dpto2Danes.isSelected()) msj+= " " + dpto2Danes.getText();
            if(localDanes.isSelected()) msj+= " " + localDanes.getText();
            if(galponDanes.isSelected()) msj+= " " + galponDanes.getText();  
        }
        
        if(agp.isSelected())
        {
            msj+= "\n " + agp.getText();
            if(casaAgp.isSelected()) msj+= " " + casaAgp.getText();
            if(dpto1Agp.isSelected()) msj+= " " + dpto1Agp.getText();
            if(dpto2Agp.isSelected()) msj+= " " + dpto2Agp.getText();
            if(localAgp.isSelected()) msj+= " " + localAgp.getText();
            if(galponAgp.isSelected()) msj+= " " + galponAgp.getText();  
        }
        
        if(mutual.isSelected())
        {
            msj+= "\n " + mutual.getText();
            if(casaMutual.isSelected()) msj+= " " + casaMutual.getText();
            if(dpto1Mutual.isSelected()) msj+= " " + dpto1Mutual.getText();
            if(dpto2Mutual.isSelected()) msj+= " " + dpto2Mutual.getText();
            if(localMutual.isSelected()) msj+= " " + localMutual.getText();
            if(galponMutual.isSelected()) msj+= " " + galponMutual.getText();   
        }
               
        if(cgt.isSelected())
        {
            msj+= "\n " + cgt.getText();
            if(casaCgt.isSelected()) msj+= " " + casaCgt.getText();
            if(dpto1Cgt.isSelected()) msj+= " " + dpto1Cgt.getText();
            if(dpto2Cgt.isSelected()) msj+= " " + dpto2Cgt.getText();
            if(localCgt.isSelected()) msj+= " " + localCgt.getText();
            if(galponCgt.isSelected()) msj+= " " + galponCgt.getText();   
        }
        
        if(ch2.isSelected())
        {
            msj+= "\n " + ch2.getText();
            if(casaCh2.isSelected()) msj+= " " + casaCh2.getText();
            if(dpto1Ch2.isSelected()) msj+= " " + dpto1Ch2.getText();
            if(dpto2Ch2.isSelected()) msj+= " " + dpto2Ch2.getText();
            if(localCh2.isSelected()) msj+= " " + localCh2.getText();
            if(galponCh2.isSelected()) msj+= " " + galponCh2.getText();   
        }
        
        JOptionPane.showMessageDialog(rootPane, msj);
    }//GEN-LAST:event_aceptarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        
        principal obj = new principal();
        
        obj.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JRadioButton agp;
    private javax.swing.JRadioButton casaAgp;
    private javax.swing.JRadioButton casaCgt;
    private javax.swing.JRadioButton casaCh2;
    private javax.swing.JRadioButton casaDanes;
    private javax.swing.JRadioButton casaIntevu;
    private javax.swing.JRadioButton casaMutual;
    private javax.swing.JButton cerrar;
    private javax.swing.JRadioButton cgt;
    private javax.swing.JRadioButton ch2;
    private javax.swing.JRadioButton danes;
    private javax.swing.JRadioButton dpto1Agp;
    private javax.swing.JRadioButton dpto1Cgt;
    private javax.swing.JRadioButton dpto1Ch2;
    private javax.swing.JRadioButton dpto1Danes;
    private javax.swing.JRadioButton dpto1Intevu;
    private javax.swing.JRadioButton dpto1Mutual;
    private javax.swing.JRadioButton dpto2Agp;
    private javax.swing.JRadioButton dpto2Cgt;
    private javax.swing.JRadioButton dpto2Ch2;
    private javax.swing.JRadioButton dpto2Danes;
    private javax.swing.JRadioButton dpto2Intevu;
    private javax.swing.JRadioButton dpto2Mutual;
    private javax.swing.JRadioButton galponAgp;
    private javax.swing.JRadioButton galponCgt;
    private javax.swing.JRadioButton galponCh2;
    private javax.swing.JRadioButton galponDanes;
    private javax.swing.JRadioButton galponIntevu;
    private javax.swing.JRadioButton galponMutual;
    private javax.swing.JRadioButton intevu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton localAgp;
    private javax.swing.JRadioButton localCgt;
    private javax.swing.JRadioButton localCh2;
    private javax.swing.JRadioButton localDanes;
    private javax.swing.JRadioButton localIntevu;
    private javax.swing.JRadioButton localMutual;
    private javax.swing.JRadioButton mutual;
    private javax.swing.ButtonGroup tipoAgp;
    private javax.swing.ButtonGroup tipoCgt;
    private javax.swing.ButtonGroup tipoCh2;
    private javax.swing.ButtonGroup tipoDanes;
    private javax.swing.ButtonGroup tipoIntevu;
    private javax.swing.ButtonGroup tipoMutual;
    // End of variables declaration//GEN-END:variables
}
