/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

/**
 *
 * @author Rodrigo Velo
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deportes = new javax.swing.JButton();
        btnRadioButton = new javax.swing.JButton();
        ej5 = new javax.swing.JButton();
        ej6 = new javax.swing.JButton();
        ej7 = new javax.swing.JButton();
        ej8 = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu de Opciones");

        deportes.setText("Deportes");
        deportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deportesActionPerformed(evt);
            }
        });

        btnRadioButton.setText("Radio Button");
        btnRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadioButtonActionPerformed(evt);
            }
        });

        ej5.setText("Ejercicio 5");
        ej5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej5ActionPerformed(evt);
            }
        });

        ej6.setText("Ejercicio 6");
        ej6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej6ActionPerformed(evt);
            }
        });

        ej7.setText("Ejercicio 7");
        ej7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej7ActionPerformed(evt);
            }
        });

        ej8.setText("Ejercicio 8");
        ej8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ej8ActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jButton1.setText("Spinner");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(deportes)
                    .addComponent(btnRadioButton)
                    .addComponent(ej5)
                    .addComponent(ej6)
                    .addComponent(ej7)
                    .addComponent(ej8)
                    .addComponent(jLabel1)
                    .addComponent(cerrar)
                    .addComponent(jButton1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ej5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ej6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ej7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ej8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deportesActionPerformed
        // TODO add your handling code here:
        deportes dep = new deportes();
        
        dep.setVisible(true);
         
        this.dispose();
    }//GEN-LAST:event_deportesActionPerformed

    private void btnRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadioButtonActionPerformed
        // TODO add your handling code here:
        radioButton rad = new radioButton();
        
        rad.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnRadioButtonActionPerformed

    private void ej5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej5ActionPerformed
        // TODO add your handling code here:
        ejercicio5 ej5 = new ejercicio5();
        
        ej5.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ej5ActionPerformed

    private void ej6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej6ActionPerformed
        // TODO add your handling code here:
        ejercicio6 ej6 = new ejercicio6();
        
        ej6.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ej6ActionPerformed

    private void ej7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej7ActionPerformed
        // TODO add your handling code here:
        
        ejercicio7 ej7 = new ejercicio7();
        
        ej7.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ej7ActionPerformed

    private void ej8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ej8ActionPerformed
        // TODO add your handling code here:
        
        ejercicio8 ej8 = new ejercicio8();
        
        ej8.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_ej8ActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Spinner spi = new Spinner();
        
        spi.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRadioButton;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton deportes;
    private javax.swing.JButton ej5;
    private javax.swing.JButton ej6;
    private javax.swing.JButton ej7;
    private javax.swing.JButton ej8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
