/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Velo
 */
public class radioButton extends javax.swing.JFrame {

    /**
     * Creates new form radioButton
     */
    public radioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postres = new javax.swing.ButtonGroup();
        principales = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        helado = new javax.swing.JRadioButton();
        torta = new javax.swing.JRadioButton();
        gelatina = new javax.swing.JRadioButton();
        chocotorta = new javax.swing.JRadioButton();
        flan = new javax.swing.JRadioButton();
        tiramisu = new javax.swing.JRadioButton();
        pizza = new javax.swing.JRadioButton();
        milanesa = new javax.swing.JRadioButton();
        lomito = new javax.swing.JRadioButton();
        empanada = new javax.swing.JRadioButton();
        ñoqui = new javax.swing.JRadioButton();
        asado = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Comidas Favoritas");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 3, 12)); // NOI18N
        jLabel2.setText("Postres:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 3, 12)); // NOI18N
        jLabel3.setText("Platos Principales:");

        postres.add(helado);
        helado.setText("Helado");

        postres.add(torta);
        torta.setText("Torta");

        postres.add(gelatina);
        gelatina.setText("Gelatina");

        postres.add(chocotorta);
        chocotorta.setText("Chocotorta");

        postres.add(flan);
        flan.setText("Flan");

        postres.add(tiramisu);
        tiramisu.setText("Tiramisu");

        principales.add(pizza);
        pizza.setText("Pizza");

        principales.add(milanesa);
        milanesa.setText("Milanesa a la napolitana");
        milanesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milanesaActionPerformed(evt);
            }
        });

        principales.add(lomito);
        lomito.setText("Lomito");

        principales.add(empanada);
        empanada.setText("Empanada");

        principales.add(ñoqui);
        ñoqui.setText("Ñoqui");

        principales.add(asado);
        asado.setText("Asado");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(helado)
                .addGap(11, 11, 11)
                .addComponent(chocotorta))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(torta)
                .addGap(22, 22, 22)
                .addComponent(flan))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(gelatina)
                .addGap(6, 6, 6)
                .addComponent(tiramisu))
            .addComponent(jLabel3)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(pizza)
                .addGap(18, 18, 18)
                .addComponent(asado))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lomito)
                .addGap(6, 6, 6)
                .addComponent(ñoqui))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(empanada))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(milanesa))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(aceptar)
                .addGap(11, 11, 11)
                .addComponent(limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cerrar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(helado)
                    .addComponent(chocotorta))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(torta)
                    .addComponent(flan))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gelatina)
                    .addComponent(tiramisu))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pizza)
                    .addComponent(asado))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lomito)
                    .addComponent(ñoqui))
                .addGap(6, 6, 6)
                .addComponent(empanada)
                .addGap(6, 6, 6)
                .addComponent(milanesa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(limpiar)
                    .addComponent(cerrar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void milanesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milanesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milanesaActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        String msj1 = "Usted elijio el postre: ";
        String msj2 = "Usted elijio el plato principal: ";    
        
        
        if(helado.isSelected())
        {
            msj1+=helado.getText()+"\n";
        }
        
        if(chocotorta.isSelected())
        {
            msj1+=chocotorta.getText()+"\n";
        }
        
        if(flan.isSelected())
        {
            msj1+=flan.getText()+"\n";
        }
        
        if(gelatina.isSelected())
        {
            msj1+=gelatina.getText()+"\n";
        }
        
        if(tiramisu.isSelected())
        {
            msj1+=tiramisu.getText()+"\n";
        }
        
        if(asado.isSelected())
        {
            msj2+=asado.getText()+"\n";
        }
        
        if(empanada.isSelected())
        {
            msj2+=empanada.getText()+"\n";
        }
        
        if(lomito.isSelected())
        {
            msj2+=lomito.getText()+"\n";
        }
        
        if(milanesa.isSelected())
        {
            msj2+=milanesa.getText()+"\n";
        }        
        
        if(pizza.isSelected())
        {
            msj2+=pizza.getText()+"\n";
        }
        
        if(ñoqui.isSelected())
        {
            msj2+=ñoqui.getText()+"\n";
        }
        
        JOptionPane.showMessageDialog(rootPane, msj1+"\n"+msj2);
    }//GEN-LAST:event_aceptarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        postres.clearSelection();
        principales.clearSelection();
        
    }//GEN-LAST:event_limpiarActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        
        principal obj = new principal();
        
        obj.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JRadioButton asado;
    private javax.swing.JButton cerrar;
    private javax.swing.JRadioButton chocotorta;
    private javax.swing.JRadioButton empanada;
    private javax.swing.JRadioButton flan;
    private javax.swing.JRadioButton gelatina;
    private javax.swing.JRadioButton helado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton lomito;
    private javax.swing.JRadioButton milanesa;
    private javax.swing.JRadioButton pizza;
    private javax.swing.ButtonGroup postres;
    private javax.swing.ButtonGroup principales;
    private javax.swing.JRadioButton tiramisu;
    private javax.swing.JRadioButton torta;
    private javax.swing.JRadioButton ñoqui;
    // End of variables declaration//GEN-END:variables
}
