/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guia2;

/**
 *
 * @author Rodrigo Velo
 */
public class Spinner extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio9
     */
    public Spinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        litoral = new javax.swing.JSpinner();
        norte = new javax.swing.JSpinner();
        centro = new javax.swing.JSpinner();
        patagonia = new javax.swing.JSpinner();
        ver = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Control Spinner");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 7, -1, -1));

        jLabel2.setText("Patagonia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, -1, -1));

        jLabel3.setText("Litoral");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, -1, -1));

        jLabel4.setText("Norte");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, -1));

        jLabel5.setText("Centro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, -1, -1));

        litoral.setModel(new javax.swing.SpinnerListModel(new String[] {"Corrientes", "Misiones", "Entre Rios", "Chaco", "Formosa", "Santa Fe"}));
        getContentPane().add(litoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 66, 175, -1));

        norte.setModel(new javax.swing.SpinnerListModel(new String[] {"Catamarca", "Jujuy", "Salta", "Santiago del Estero", "Tucuman"}));
        norte.setToolTipText("");
        getContentPane().add(norte, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 94, 175, -1));

        centro.setModel(new javax.swing.SpinnerListModel(new String[] {"Cordoba", "Buenos Aires", "La pampa"}));
        getContentPane().add(centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 122, 175, -1));

        patagonia.setModel(new javax.swing.SpinnerListModel(new String[] {"Neuquen", "Chubut", "Rio Negro", "Santa Cruz", "Tierra del fuego", "Antartida"}));
        patagonia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(patagonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 35, 175, -1));

        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        getContentPane().add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 162, 53, -1));

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 162, -1, -1));

        mostrar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mostrar.setEnabled(false);
        jScrollPane1.setViewportView(mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, 234, 96));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
        String msj = "Patagonia: " + patagonia.getValue() +
                "\nLitoral: " +  litoral.getValue() +
                "\nNorte: " + norte.getValue() + 
                "\nCentro: " + centro.getValue();
        
        mostrar.setText(msj);
        
    }//GEN-LAST:event_verActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        principal obj = new principal();
        
        obj.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spinner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner centro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner litoral;
    private javax.swing.JTextPane mostrar;
    private javax.swing.JSpinner norte;
    private javax.swing.JSpinner patagonia;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
